### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by TheMythFlex** [mbcmkay/Xbox-followers-tool#1]
hey there this is not related to ur project I just need some info if u don't mind

I'm making an Xbox Gamer tag claimer what I need to know is how can I get Xbox tokens 

i made an Xbox account generator but i can't figure out where to get the tokens from 

token looks like this : 

XBL3.0 x=6003166259875390760;eyJlbmMiOiJBMTI4Q0JDK0hTMjU2IiwiYWxnIjoiUlNBLU9BRVAiLCJjdHkiOiJKV1QiLCJ6aXAiOiJERUYiLCJ4NXQiOiIxZlVBejExYmtpWklFaE5KSVZnSDFTdTVzX2cifQ.fy3jSSdYBCGipjo1trRnm6tPDrGl61wKJAeweTx5HgMYe9_kfDhYVZ_ApSoT3fRaVAzyfOHo-ZfriAeOD87h5nZxFrAzrHVlRWszK4Vl9iDaHE7vuWt9V-rAh6n3M8OyIVs3Q7P7zm53yyigaxa_ODxpWgDSfOz17vVOfvKN_xw.WBdY995t4PbfvqdfwItPyw.rcgUDApYOlCn_etisLCO92XJU0mQtgHhwzgiPtobzcf-Y9ICSzFLnx3kHNSRtnCTcONxQRROc-Qn-i9NQRx6_z_XU_iFyLVMvd03RRfhNASeoWsDbwWGjI-zeAHoH0_XqsQP7f7FxixIYf1iABylVOuSQ01q9xiD2LhwQ3kPa8_10sXowGvPB7cW3k3AfpJD1gEbBcE20HwABl4vgfAAUX2iPNFThPFL1Ys6M6aRKulm76xZRTvvOdF1_uxh5ztFlY6GsR-FlEoQNgguBK6iGKa8KIheV0AdDKosfEOO3FdWOp-1V-EuqwbsCnkXErzLUPraYOodgDdZldEgwMZfo8zz3QiTL61xndWt1f9BDdn_mY8cMl5eyQDmstMhP3h9uKqop1nfdHUYe9-dxEjx6xtrezrU8RqF7v7JkVTuocD0w2Um0pPLAjNvCB52EgyHt1GCvpBAXo8yLeIFXAmlaVLoJzjao7_45YaEHXFd3_g09N24h7gsAKC3gQy-xJR3JT86z4QWgsaqIF0EzMMoiUR6SikL4mSOf3_vFDN65bsXPRkljVP7gpjUu8sYIr2OiWrew1yNd-7q85cAeIwIeN1y4gSn-8-awW0dKJAXAsJEK2Myof_wgPnC4alSS4nh-zhZG6WlKcJv-zjXqxicJfWtGY6NUL43FA2oIH5n2bGfKi9F28WvYZt0YR137tXj9WfvwDMfMXnMmQ-QL66m4JxIX7UFBrA8ggemuM33P9G6bxAFNEfFWkSBC4iIpytmU3j1ABOlnaEbJ6EiolGIsisWRYR7anqFEi-JeEInfAoSSxiKhcXUC3m_DgNoStmqpnYUINwc80O5v_OaEehrUKjZ-PSWiKWpw0NLAKgEjDRY2ZvSPJuwhhDIcOaBEz__dXHVB2JoTL56a3pUPKYRRU7rGXXdAKnNmV2uIdrZcctJaaRYuPutFBA3T2hBWmNEkrTeQPLFFR2jfzg4V8dA98vYMicsH9jcQn3zR8txXPFA8qRU3cSivb030T-8DvQ8_f2Rwnrr2w86gClSsUswHhEW2UpympKwnsnCBrWpfmpGo7GuLiHWenFq1OIehfuCo3NVpIqnX2N6wqij3-GSj398M0vNBiLbiaZ9yuTSqO6ukXLeaoOsor9Ab8Dy6FTXQxgvucN_foufdX6V_RUMVecKs8aa_AY1XUXYdelWpGXe4cWRYdioWYZmIXXhb9w1-1mL0MVWamhAdBnEnV6h_mx-WHnGXXLLmwMcw0OU8T0TovXeRGjAQcWNoF-e1t2YpAXhZXV0gTzRXMVEW3N1-RBWrW4Q__muCsx_vknb9jWvf7iGbyBnDXKiSoIQMRSwTvjAslRFPUC5HXSDbWuYDRaFnPVdyiHo5HR8lmXjA4dKKA_KEpywesmR6zaBK99aXNVDo379K1xvrBjmm-cKEdxQC_3Y4SU_uJE5QSF2o6oP93FDiqDUYuWHJVaKiO7lnhJGU-cv8Kjrt6Fk_an0jQ.0n3a8w9Ks9V_nkocwzXP-FbgyUxGS400gIq7JmIjmCY

**Comment by mbcmkay** [comment]
Hello the token you have sent me is the correct token unless you mean where to get the tokens from after generating the accounts?

If you need more help join my Discord server.

**Comment by TheMythFlex** [comment]
yes, where do i get the tokens from?

**Comment by TheMythFlex** [comment]
just added on discord
